#!/usr/bin/env bash
# Resolve which /dev/fbN is the SPI panel and write the X fbdev config.
# Runs as ExecStartPre=+ (root) of the X11 kiosk unit: framebuffer numbering
# is not stable across boots (vc4, the firmware BCM2708 FB, and fbtft race
# for fb0), and the X fbdev driver rejects symlinks, so the real node has to
# be resolved at startup.
set -euo pipefail

# fbtft panel names look like "fb_ili9486"; firmware/KMS ones are "BCM2708 FB",
# "vc4drmfb", "simplefb" etc. Prefer the fbtft entry, fall back to fb0.
FB_NUM="$(awk '$2 ~ /^fb_/ {print $1; exit}' /proc/fb)"
FB_DEV="/dev/fb${FB_NUM:-0}"

mkdir -p /etc/X11/xorg.conf.d
cat > /etc/X11/xorg.conf.d/99-fbdev.conf <<EOF
# Generated by set-fbdev.sh at kiosk startup: do not edit; panel resolved
# from /proc/fb. Screen/ServerLayout are required or X autoconfig probes KMS
# and dies with "no screens found".
Section "Device"
  Identifier "FBDEV"
  Driver "fbdev"
  Option "fbdev" "${FB_DEV}"
EndSection

Section "Screen"
  Identifier "FBSCREEN"
  Device "FBDEV"
EndSection

Section "ServerLayout"
  Identifier "LAYOUT"
  Screen "FBSCREEN"
EndSection
EOF

echo "fbdev: using ${FB_DEV} ($(grep "^${FB_NUM:-0} " /proc/fb || true))"
